tracker/home/urls.py
from django.urls import include, path

from home.views import HomeView, AboutView, AdminView

app_name = 'home'

urlpatterns = [
    path('admin/', AdminView.as_view(), name='admin'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomeView.as_view(), name='home')
]

tracker/tasks/admin/urls.py
from django.urls import include, path

from tasks.views import TaskTypeView, TaskView, TaskDependencyView, FiltersView

app_name = 'admin_tasks'

urlpatterns = [
    path('types/', TaskTypeView.as_view(), name='tasktype-list'),
    path('type/add/', TaskTypeView.as_view(), {"action":"add"}, name='tasktype-detail'),
    path('type/<int:pk>/change/', TaskTypeView.as_view(), {"action":"change"}, name='tasktype-detail'),
    path('type/<int:pk>/delete/', TaskTypeView.as_view(), {"action":"delete"}, name='tasktype-delete'),

    path('filters/', FiltersView.as_view(), name='filters-list'),
    path('filters/add/', FiltersView.as_view(), {"action":"add"}, name='filters-detail'),
    path('filters/<int:pk>/change/', FiltersView.as_view(), {"action":"change"}, name='filters-detail'),
    path('filters/<int:pk>/delete/', FiltersView.as_view(), {"action":"delete"}, name='filters-delete'),

    path('taskdependency/', TaskDependencyView.as_view(), name='taskdependency-list'),
    path('taskdependency/add/', TaskDependencyView.as_view(), {"action":"add"}, name='taskdependency-detail'),
    path('taskdependency/<int:pk>/change/', TaskDependencyView.as_view(), {"action":"change"}, name='taskdependency-detail'),
    path('taskdependency/<int:pk>/delete/', TaskDependencyView.as_view(), {"action":"delete"}, name='taskdependency-delete'),
]

tracker/tasks/urls.py
from django.urls import include, path

from tasks.views import TaskTypeView, TaskView

app_name = 'tasks'

urlpatterns = [
    path('create/', TaskView.as_view(), {"action": "create" }, name='create'),
    path('search/', TaskView.as_view(), {"action": "search" }, name='search'),
    path('browse/<task_key>/', TaskView.as_view(), {"action":"browse"}, name='browse'),
    path('browse/<task_key>/edit/', TaskView.as_view(), {"action":"edit"}, name='edit'),
]

tracker/tracker/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/projects/', include('projects.urls', namespace='projects')),
    path('admin/workflow/', include('workflows.urls', namespace='workflows')),
    path('admin/tasks/', include('tasks.admin.urls', namespace='admin_tasks')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', include('home.urls', namespace='home')),
    path('djadmin/', admin.site.urls),
]

tracker/tasks/forms.py
from django import forms

from tasks.models import TaskType, Task, Filters, Attachments, Comments, TaskDependency

class TaskTypeForm(forms.ModelForm):
    ui_fields = ['id', 'name', 'workflow__name']
    link = "name"

    class Meta:
        model = TaskType
        exclude = ('created_on', 'modified_on', 'created_by', 'modified_by')

class TaskForm(forms.ModelForm):
    parent = forms.CharField(widget=forms.HiddenInput(attrs={"initial": None}), required=False)
    class Meta:
        model = Task
        exclude = ('created_on', 'modified_on', 'created_by', 'modified_by')

class TaskDependencyForm(forms.ModelForm):
    ui_fields = ['id', 'name', 'inward', 'outward']
    link = 'name'

    class Meta:
        model = TaskDependency
        exclude = ('created_on', 'modified_on', 'created_by', 'modified_by')

class FiltersForm(forms.ModelForm):
    ui_fields = ['id', 'name', 'fields', 'ordering']
    link = "name"
    
    class Meta:
        model = Filters
        exclude = ('created_on', 'modified_on', 'created_by', 'modified_by')


class AttachmentsForm(forms.ModelForm):
    class Meta:
        model = Attachments
        exclude = ('task', 'created_on', 'created_by')


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        widgets = {
            'comment': forms.Textarea(attrs={"rows": 3})
        }
        exclude = ('task', 'created_on', 'modified_on', 'created_by', 'modified_by')

tracker/tasks/views.py
import logging

from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.http.response import HttpResponse
from home.base_views import BaseView
from projects.models import Project
from tasks.models import TaskType, Task, Filters, Comments, TaskDependency, Attachments, TaskDependencyMapping
from workflows.models import WorkflowStates
from accounts.models import User
from tasks.forms import TaskTypeForm, TaskForm, FiltersForm, CommentsForm, AttachmentsForm, TaskDependencyForm
from projects.models import Project
from django.db.models import Q
from django.shortcuts import redirect, reverse
from tasks.filters.task_filters import TaskFilters


logger = logging.getLogger(__name__)

# Create your views here.
class TaskTypeView(BaseView):
    form = TaskTypeForm
    model = TaskType
    app = "admin_tasks"
    model_name = "Task Type"


class FiltersView(BaseView):
    form = FiltersForm
    model = Filters
    app = "admin_tasks"
    model_name = "Filters"

class TaskDependencyView(BaseView):
    form = TaskDependencyForm
    model = TaskDependency
    app = "admin_tasks"
    model_name = "Task Dependency"


class TaskView(View):
    template = "task-create.html"
    fields = ['key', 'project__name', 'tasktype__name', 'summary', 'priority', 'state']
    form = TaskForm

    def create(self, request, task_key=None, *args, **kwargs):
        if task_key is None:
            form = self.form()
            action = action_button="Add New"
        else:
            task = Task.objects.get(key=task_key)
            form = self.form(instance=task, initial={'parent': task_key})
            action = "Change"
            action_button = "Update"
        context={
            "form" : form,
            "action": action,
            "task_key": task_key,
            "action_button": action_button
        }
        return render(request, self.template, context)

    def get_filter_data(self, request, task_filter):
        filter_obj = Filters.objects.get(id=task_filter)
        fields = filter_obj.fields.split(", ")
        fields_list = [row.strip().split("=") for row in fields]
        fields_pattern = {k:v for k,v in fields_list}
        for k, v in fields_pattern.items():
            if v.endswith('()'):
                fields_pattern[k] = getattr(TaskFilters, v.rstrip('()'))(request)
            elif "," in v:
                fields_pattern[k] = v.split(",")
        queryset = Task.objects.filter(**fields_pattern).values(*self.fields)
        return list(queryset)

    def get_tasks_by_project(self, name):
        try:
            project = Project.objects.get(name=name)        #noqa : Django Queryset
            queryset = Task.objects.filter(project=project)   #noqa : Django Queryset
            queryset = list(queryset.values(*self.fields))
        except Exception as e:
            logger.exception(e)
            queryset = []
        finally:
            return queryset

    def get_task_by_key(self, key):
        try:
            name, task_id = key.split("-")
            project = Project.objects.get(key=name)         #noqa : Django Queryset
            queryset = Task.objects.filter(project=project, tasknum=task_id)    #noqa : Django Queryset
            queryset = list(queryset)
        except Exception as e:
            logger.exception(e)
            queryset = []
        finally:
            return queryset

    def get_task_by_text(self, text):
        return list(Task.objects.filter(Q(summary__contains = text) | Q(description__contains = text)).values_list(*self.fields))

    def get_tasks_by_tasktype(self, name):
        try:
            tasktype = TaskType.objects.get(name=name)          # noqa : Django Queryset
            queryset = Task.objects.filter(tasktype=tasktype)   # noqa : Django Queryset
            queryset = list(queryset.values(*self.fields))
        except Exception as e:
            logger.exception(e)
            queryset = []
        finally:
            return queryset

    def get_tasks(self):
        return list(Task.objects.all().values(*self.fields))

    def browse(self, request, task_key, *args, **kwargs):
        template="task-browse.html"
        context={}
        obj = None
        error = None
        buttons = []
        try:
            obj = Task.objects.get(key=task_key)
            transitions = obj.tasktype.get_avilable_transitions(obj.state)
            comments = Comments.objects.filter(task=obj.id).values('comment', 'created_by__username')
            attachments = Attachments.objects.filter(task=obj.id).values('file_path')
            task_dependency=TaskDependency.objects.get(name='subtask')
            outward_tasks = TaskDependencyMapping.objects.filter(task=obj, dependency_type=task_dependency)
            outward_tasks = [ { "key": row.dependent_task.key, "summary": row.dependent_task.summary, "type": task_dependency.outward } for row in outward_tasks ]

            inward_tasks = TaskDependencyMapping.objects.filter(dependent_task=obj, dependency_type=task_dependency)
            inward_tasks = [ { "key": row.task.key, "summary": row.task.summary, "type": task_dependency.inward } for row in inward_tasks ]
            
            subtasks = outward_tasks + inward_tasks

            new_comments_form = CommentsForm()
            upload_attachments_form = AttachmentsForm()

            task_options = [
                { "name" : "edit", },
                { "name" : "create subtask" }
            ]
            for row in transitions:
                buttons.append(
                    { "name": row }
                )

            workflow_options = buttons
            context["task_options"] = task_options
            context["workflow_options"] = workflow_options
            context["comments"] = comments
            context["attachments"] = attachments
            context["new_comments_form"] = new_comments_form
            context["upload_attachments_form"] = upload_attachments_form
            context["subtasks"] = subtasks

        except Exception as e:
            logger.exception(e)
            error = f"The requested resource {task_key} is either invalid or not found.!!!"
        finally:
            context["obj"] = obj
            context["error"] = error
            return render(request, template, context)

    def get_tasks_detail(self, project_name, tasktype):
        try:
            project = Project.objects.get(name=project_name)        #noqa : Django Queryset
            tasktype = TaskType.objects.get(name=tasktype)        #noqa : Django Queryset
            queryset = Task.objects.filter(project=project, tasktype=tasktype)   #noqa : Django Queryset
            queryset = list(queryset.values(*self.fields))
        except Exception as e:
            logger.exception(e)
            queryset = []
        finally:
            return queryset

    def search(self, request, *args, **kwargs):
        context = {}
        local_context = {}
        try:
            logger.info("Searching Tasks")
            template="task-list.html"
            project_name = request.GET.get("project")
            task_filter = request.GET.get("filter")
            task_key = request.GET.get("key")
            text = request.GET.get("text")
            tasktype = request.GET.get("tasktype")

            name = f"{project_name} Tasks"

            if project_name and tasktype:
                queryset = self.get_tasks_detail(project_name, tasktype)
                name = f"{project_name} - {tasktype}"
            elif task_filter:
                queryset = self.get_filter_data(request, task_filter)
                name = "%s Tasks" %(Filters.objects.get(id=task_filter).name)
            elif project_name:
                queryset = self.get_tasks_by_project(name=project_name)
            elif tasktype:
                queryset = self.get_tasks_by_tasktype(name=tasktype)
                name = f"{tasktype} Tasks"
            elif task_key:
                queryset = self.get_task_by_key(key=task_key)
            elif text:
                queryset = self.get_task_by_text(text=text)
            else:
                logger.info("Fetching All Tasks.")
                project_list = list(Project.objects.all().values_list('name', flat=True))
                tasktype_list = list(TaskType.objects.all().values_list('name', flat=True))
                state_list = list(WorkflowStates.objects.all().values_list('name', flat=True))
                priority_list = [ row[0] for row in Task.TASK_PRIORITY]
                user_list = list(User.objects.all().values_list('username', flat=True))
                local_context = {
                    "project_list": project_list,
                    "tasktype_list": tasktype_list,
                    "state_list": state_list,
                    "priority_list": priority_list,
                    "user_list": user_list,
                }
                queryset = self.get_tasks()
                name = f"Tasks"

            context={
                "name": name,
                "queryset": queryset,
                "keys": self.fields,
                "link": "key",
            }
            context.update(local_context)
            return render(request, template, context)
        except Exception as e:
            logger.exception(e)
            template = "task-error.html"
            context["error"] = str(e)
            return render(request, template, context)

    def get(self, request, action, task_key=None, *args, **kwargs):
        if action == "create":
            return self.create(request, task_key)
        elif action == "search":
            return self.search(request, *args, **kwargs)
        elif action == 'browse':

tracker/tasks/templates/create.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}

{% block content %}
<div class="container">
    <div class="header">
        <h3 class="title"> Add Tasks </h3>
    </div>
    <div class="change">
        <form action="{% url 'tasks:create' %}" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="actions">
                <button type="submit" class="btn btn-primary"> Add New </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

tracker/tasks/templates/task-browse.html
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}

{% block content %}
<div class="container-fluid">
    {% if error %}
        <div class="error">
            <h3 class="error"> {{ error }} </h3>
        </div>
    {% else %}
        <div class="task-view">
            <div class="task-header">
                <h5 class="breadcumb">
                    <a href="{% url 'tasks:search' %}?project={{obj.project.name}}"> {{ obj.project.name | title }} </a>
                    /
                    <a href="{% url 'tasks:search' %}?project={{obj.project.name}}&tasktype={{obj.tasktype.name}}"> {{ obj.tasktype.name | title }} </a>
                    /
                    <a href="{% url 'tasks:browse' task_key=obj.key %}"> {{ obj.key }} </a>
                </h5>
                <p class="task-fields summary">
                    {{ obj.summary }}
                </p>
            </div>
            <div class="task-options">
                <a class="btn btn-primary task-option" href="{% url 'tasks:edit' obj.key %}"> Edit </a>
                <form  class="form-inline" action="{% url 'tasks:create' %}" method="post" style="display: inline-flex;">
                        {% csrf_token %}
                        <input type="text" value="true" name="parent" id="parent" hidden> </input>
                        <input type="text" value="{{ obj.key }}" name="parent_task" id="parent_task" hidden> </input>
                        <button class="btn btn-primary task-option" type="submit"> Create Sub Tasks </button>
                </form>

                {% if workflow_options|length == 1 %}
                    {% for options in workflow_options %}
                        <a class="btn dropdown-item" href="{% url 'tasks:search' %}?project={{ options.name }}"> {{ options.name }}</a>
                    {% endfor %}
                {% else %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="btn btn-primary task-option nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Workflow</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown01">
                                {% for options in workflow_options %}
                                    <a class="dropdown-item" href="{% url 'tasks:browse' obj.key %}"> {{ options.name }} </a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                {% endif %}                
            </div>
            <div class="task-body row">
                <div class="col-sm-8">
                    <div class="task-fields">
                        <label class="field-label" for="priority"> Priority: </label> {{ obj.priority }}
                    </div>
                    <div class="task-fields">
                        <label class="field-label" for="priority"> State: </label> {{ obj.state }}
                    </div>
                    <div class="task-fields">
                        <label class="field-label" for="priority"> DueDate: </label> {{ obj.due_date }}
                    </div>
                    <div class="task-fields">
                        <label class="field-label" for="priority"> Description: </label> {{ obj.description }}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="task-fields">
                        <label class="field-label" for="priority"> Assignee: </label> {{ obj.assignee }}
                    </div>
                    <div class="task-fields">
                        <label class="field-label" for="priority"> Reporter: </label> {{ obj.reporter }}
                    </div>
                    <div class="task-fields">
                        <label class="field-label" for="priority"> Watchers: </label> {{ obj.watchers }}
                    </div>
                </div>
            </div>
            <div class="subtasks-list">
                <h4> Dependent Tasks </h4>
                <table class="table table-responsive">
                    {% for row in subtasks %}
                    <tr>
                        <td> {{ row.type }} </td>
                        <td> <a href="{% url 'tasks:browse' row.key %}"> {{ row.key }}  </a></td>
                        <td> {{ row.summary }} </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="task-attachments">
                <h4> Attachments </h4>
                {% for row in attachments %}
                    <div class="attachments">
                        {{ row.file_path }}
                    </div>
                {% endfor %}
                <form method="post" action="{% url 'tasks:browse' obj.key %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ upload_attachments_form | crispy }}
                    <input class="btn btn-primary attachments-submit" type="submit" value="Attach">
                </form>
            </div>
            <div class="task-comments">
                <h4> Comments </h4>
                {% for row in comments %}
                    <div class="card comments-card">
                        <div class="card-title comment-header">
                            <h6 class="comment-owner"> Added By {{ row.created_by__username }} </h6>
                            
                        </div>
                        <div class="card-body comment-body">
                            {{ row.comment }}
                        </div>
                    </div>
                {% endfor %}
                <form action="{% url 'tasks:browse' obj.key %}" method="post">
                    {% csrf_token %}
                    {{ new_comments_form | crispy }}
                    <input class="btn btn-primary comment-submit" type="submit" value="Add Comments">
                </form>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

tracker/tasks/templates/task-create.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}

{% block content %}
<div class="container">
    
    <div class="header">
        <h3 class="title"> {{ action|title }} Task </h3>
    </div>
    <div class="change">
        {% if task_key %}
        <form action="{% url 'tasks:edit' task_key %}" method="POST">
        {% endif %}
        <form action="{% url 'tasks:create' %}" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="actions">
                <button type="submit" class="btn btn-primary"> {{action_button|title}} </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

tracker/tasks/templates/task-error.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}

{% block content %}
<div class="container">
    <div class="error">
        <h3 class="error"> {{ error  }}</h3>
    </div>
</div>
{% endblock %}

tracker/tasks/templates/task-list.html
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}


{% block customjs %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#list-data').DataTable({
                "pageLength": 50,
                "lengthMenu": [25, 50, 100, 500],
            });
        });
    </script>
{% endblock %}

{% block content %}

<div class="container">
    <div class="header">
        <h3 class="title"> {{ name | title }} </h3>
    </div>

    {% if name|lower == 'tasks' %}
    <form class="form-inline" method="post">
        {% csrf_token %}
        <div class="form-group">
            <select id="search-project" name="project" multiple="multiple" class="tasks-search">
                {% for project in project_list %}
                    <option value="{{ project }}" {% if project in search_project %} selected="selected" {% endif %}>{{ project }}</option>
                {% endfor %}
            </select>
            <select id="search-tasktype" name="tasktype" multiple="multiple" class="tasks-search">
                {% for tasktype in tasktype_list %}
                    <option value="{{ tasktype }}" {% if tasktype in search_tasktype %} selected="selected" {% endif %}>{{ tasktype }}</option>
                {% endfor %}
            </select>
            <select id="search-priority" name="priority" multiple="multiple" class="tasks-search">
                {% for priority in priority_list %}
                    <option value="{{ priority }}" {% if priority in search_priority %} selected="selected" {% endif %}>{{ priority }}</option>
                {% endfor %}
            </select>
            <select id="search-state" name="state" multiple="multiple" class="tasks-search">
                {% for state in state_list %}
                    <option value="{{ state }}" {% if state in search_state %} selected="selected" {% endif %}>{{ state }}</option>
                {% endfor %}
            </select>
            <select id="search-user" name="user" multiple="multiple" class="tasks-search">
                {% for state in user_list %}
                    <option value="{{ user }}" {% if user in search_user %} selected="selected" {% endif %}>{{ user }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-primary tasks-search" type="submit"> Search </button>
        </div>
    </form>
    {% endif %}

    <div class="list table-responsive">
        <table class="table table-striped table-hover table-border" id="list-data">
            <thead class="thead-light">
                {% for key in keys %}
                    <th class="thead-tracker">
                        {{ key|upper }}
                    </th>
                {% endfor %}
            </thead>

            <tbody>
                {% for obj in queryset %}
                    <tr> 
                        {% for k, v in obj.items %}
                            {% if k == link %}
                                <td> <a href="{% url 'tasks:browse' task_key=v %} "> {{ v }}  </a> </td>
                            {% elif k in keys %}
                                <td> {{ v }} </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block lazyjs %}
<script type="text/javascript">
    $('#search-project').multiselect({
        includeSelectAllOption: true,
        selectAllText: 'Check all!',
        selectAllValue: 'all',
        enableFiltering: true,
        maxHeight: 400,
        enableCaseInsensitiveFiltering: true,
        nonSelectedText: 'Projects'
    });
    $('#search-tasktype').multiselect({
        includeSelectAllOption: true,
        selectAllText: 'Check all!',
        selectAllValue: 'all',
        enableFiltering: true,
        maxHeight: 400,
        enableCaseInsensitiveFiltering: true,
        nonSelectedText: 'TaskType'
    });
    $('#search-priority').multiselect({
        includeSelectAllOption: true,
        selectAllText: 'Check all!',
        selectAllValue: 'all',
        enableFiltering: true,
        maxHeight: 400,
        enableCaseInsensitiveFiltering: true,
        nonSelectedText: 'Priority'
    });
    $('#search-state').multiselect({
        includeSelectAllOption: true,
        selectAllText: 'Check all!',
        selectAllValue: 'all',
        enableFiltering: true,
        maxHeight: 400,
        enableCaseInsensitiveFiltering: true,
        nonSelectedText: 'States'
    });
    $('#search-user').multiselect({
        includeSelectAllOption: true,
        selectAllText: 'Check all!',
        selectAllValue: 'all',
        enableFiltering: true,
        maxHeight: 400,
        enableCaseInsensitiveFiltering: true,
        nonSelectedText: 'Users'
    });
</script>
{% endblock %}

tracker/tasks/templates/tasks-list.html
{% extends 'headers.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Tasks {% endblock %}


{% block customjs %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#list-data').DataTable({
                "pageLength": 50,
                "lengthMenu": [25, 50, 100, 500],
            });
        });
    </script>
{% endblock %}

{% block content %}

<div class="container">
    <div class="header">
        <h3 class="title"> {{ project | title }} Tasks </h3>
    </div>
    Query Set {{ queryset }}

    <div class="list table-responsive">
        <table class="table table-striped table-hover table-border" id="list-data">
            <thead class="thead-light">
                {% for key in keys %} 
                    <th>
                        {{ key|upper }}
                    </th>
                {% endfor %}
            </thead>

            <tbody>
                {% for obj in queryset %}
                    <tr>
                        {% for k, v in obj.items %}
                            {% if k == link %}
                                <td> {{ v }} </td>
                            {% elif k in keys %}
                                <td> {{ v }} </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}