tracker/accounts/urls.py
from django.urls import path
from accounts.views import SignUpView, UpdateProfileView, ResetPasswordView, LoginView, LogoutView, TeamView, UserView

app_name = 'accounts'

urlpatterns = [
        path('login/', LoginView.as_view(), name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('signup/', SignUpView.as_view(), name='signup'),
        path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
        path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
        path('profile/', ResetPasswordView.as_view(), name='profile'),
        path('update_password/', ResetPasswordView.as_view(), name='update_password'),
        
        path('users/', UserView.as_view(), name='user-list'),
        path('user/add/', UserView.as_view(), {"action":"add"}, name='user-detail'),
        path('user/<int:pk>/change/', UserView.as_view(), {"action":"change"}, name='user-detail'),
        path('user/<int:pk>/delete/', UserView.as_view(), {"action":"delete"}, name='user-delete'),

        path('teams/', TeamView.as_view(), name='team-list'),
        path('team/add/', TeamView.as_view(), {"action": "add"}, name='team-detail'),
        path('team/<int:pk>/change/', TeamView.as_view(), {"action": "change"}, name='team-detail'),
        path('team/<int:pk>/delete/', TeamView.as_view(), {"action": "delete"}, name='team-delete'),
]

tracker/home/urls.py
from django.urls import include, path

from home.views import HomeView, AboutView, AdminView

app_name = 'home'

urlpatterns = [
    path('admin/', AdminView.as_view(), name='admin'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomeView.as_view(), name='home')
]

tracker/tasks/admin/urls.py
from django.urls import include, path

from tasks.views import TaskTypeView, TaskView, TaskDependencyView, FiltersView

app_name = 'admin_tasks'

urlpatterns = [
    path('types/', TaskTypeView.as_view(), name='tasktype-list'),
    path('type/add/', TaskTypeView.as_view(), {"action":"add"}, name='tasktype-detail'),
    path('type/<int:pk>/change/', TaskTypeView.as_view(), {"action":"change"}, name='tasktype-detail'),
    path('type/<int:pk>/delete/', TaskTypeView.as_view(), {"action":"delete"}, name='tasktype-delete'),

    path('filters/', FiltersView.as_view(), name='filters-list'),
    path('filters/add/', FiltersView.as_view(), {"action":"add"}, name='filters-detail'),
    path('filters/<int:pk>/change/', FiltersView.as_view(), {"action":"change"}, name='filters-detail'),
    path('filters/<int:pk>/delete/', FiltersView.as_view(), {"action":"delete"}, name='filters-delete'),

    path('taskdependency/', TaskDependencyView.as_view(), name='taskdependency-list'),
    path('taskdependency/add/', TaskDependencyView.as_view(), {"action":"add"}, name='taskdependency-detail'),
    path('taskdependency/<int:pk>/change/', TaskDependencyView.as_view(), {"action":"change"}, name='taskdependency-detail'),
    path('taskdependency/<int:pk>/delete/', TaskDependencyView.as_view(), {"action":"delete"}, name='taskdependency-delete'),
]

tracker/tasks/urls.py
from django.urls import include, path

from tasks.views import TaskTypeView, TaskView

app_name = 'tasks'

urlpatterns = [
    path('create/', TaskView.as_view(), {"action": "create" }, name='create'),
    path('search/', TaskView.as_view(), {"action": "search" }, name='search'),
    path('browse/<task_key>/', TaskView.as_view(), {"action":"browse"}, name='browse'),
    path('browse/<task_key>/edit/', TaskView.as_view(), {"action":"edit"}, name='edit'),
]

tracker/tracker/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/projects/', include('projects.urls', namespace='projects')),
    path('admin/workflow/', include('workflows.urls', namespace='workflows')),
    path('admin/tasks/', include('tasks.admin.urls', namespace='admin_tasks')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', include('home.urls', namespace='home')),
    path('djadmin/', admin.site.urls),
]

tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {{ page_title | default:"Project Management" }}
        {% endblock title %}
    </title>

    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="{% static 'css/tracker.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-multiselect.css' %}" />
    {% endblock %}

    {% block js %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap-multiselect.js' %}"></script>
        
    {% endblock %}

    {% block customjs %}
    {% endblock customjs %}
</head>
<body>
    {% block header %}
        <nav>
            PlaceHolder for Headers, Replace it with actual Content..!!
        </nav>
    {% endblock header %}
    <main role="main">
        {% block content %}
        {% endblock content %}
    </main>

    {% block footer %}
    {% endblock %}

    {% block lazyjs %}
    {% endblock lazyjs %}
</body>
</html>

tracker/templates/change.html
{% extends 'admin.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block right_pane %}
    <div class="right-pane header">
        <h3 class="title"> {{ action | title }} {{ model | title }} </h3>
    </div>
    <div class="right-pane change">
        {% if form.instance.pk %}
            <form action="{% url namespace|add:':'|add:model|cut:' '|lower|add:'-detail' pk=form.instance.pk %}" method="POST">
        {% else %}
            <form action="{% url namespace|add:':'|add:model|cut:' '|lower|add:'-detail' %}" method="POST">
        {% endif %}
            {% csrf_token %}
            {{ form | crispy }}
            <div class="actions">
                <button type="submit" class="btn btn-primary"> {% if form.instance.pk %} Update {% else %} Add New {% endif %}</button>
                {% if form.instance.pk %}
                    <a class="ml-auto btn delete-link btn-danger" href="{% url namespace|add:':'|add:model|cut:' '|lower|add:'-delete' pk=form.instance.pk %}" class="deletelink"> Delete </a>
                {% endif %}
            </div>
        </form>
    </div>
    
{% endblock %}

tracker/templates/headers.html
{% extends 'base.html' %}
{% load static %}
{% load extras %}

{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark sticky-top bg-primary">
  {% block logo %}
    <a class="navbar-brand" href="{% url 'home:home' %}">
      <img src="{% static 'images/header.png' %}" alt="" srcset="" width="120px">
    </a>
  {% endblock logo %}

  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsTrackerDefault" aria-controls="navbarsTrackerDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->
  <div class="navbar collapse navbar-collapse">
    {% if user.is_authenticated %}
      {% block nav-icons %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            {% for project in request.session|get_value:user.username|get_value:"projects" %}
              <a class="dropdown-item" href="{% url 'tasks:search' %}?project={{ project.name | urlencode }}"> {{ project.name }}</a>
            {% endfor %}
          </div>
        </li>
        <li class="nav-item dropdown">
            
            <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Issues</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'tasks:search' %}"> Issues </a>
              <div class="dropdown-divider"> </div>
              {% for filter in request.session|get_value:user.username|get_value:"filters" %}
                <a class="dropdown-item" href="{% url 'tasks:search' %}?filter={{ filter.id }}"> {{ filter.name }} </a>
              {% endfor %}
              <div class="dropdown-divider"> </div>
              <a class="dropdown-item" href="{% url 'admin_tasks:filters-list' %}"> Filters </a>
              <a class="dropdown-item" href="{% url 'admin_tasks:filters-detail' %}"> Create Filters </a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link btn btn-primary" href="{% url 'tasks:create' %}"> Create </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" href="{% url 'home:about' %}"> About Us </a>
        </li>
      </ul>
      {% endblock nav-icons %}

      {% block search-bar %}
      <form class="form-inline my-4 my-lg-0" action="{% url 'tasks:search' %}", method="GET">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      </form>
      {% endblock search-bar %}
      

      {% block userinfo %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              {{ user|upper }} <span class="caret"> </span>
            </a>
            <div class="dropdown-menu">
              {% if user and user.is_superuser %}
                <a class="dropdown-item" href="{% url 'home:admin' %}">Administration</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'accounts:profile' %}">Update Profile</a>
              <a class="dropdown-item" href="{% url 'accounts:update_password' %}">Update Password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        </li>
      </ul>
      {% endblock userinfo %}
    {% else %}
    <div class="ml-auto">
      {% block signin %}
        <button type="button" class="btn" data-toggle="modal" data-target="#loginModal"> SignIn </button>
      {% endblock signin %}
      {% block signup %}
        <a href="{% url 'accounts:signup' %}" class="btn"> SignUp </a>
      {% endblock signup %}
    </div>
    {% endif %}
    </div>
  </nav>
{% endblock header %}

tracker/templates/list.html
{% extends 'admin.html' %}
{% load static %}

{% block customjs %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#list-data').DataTable({
                "pageLength": 50,
                "lengthMenu": [25, 50, 100, 500],
            });
        });
    </script>
{% endblock %}

{% block right_pane %}
    <!-- Adding Search Bar -->
    <!-- Adding Tables -->

    <div class="header">
        <h3 class="title"> {{ model | title }} List </h3>
        <a class="add-new" href="{% url namespace|add:':'|add:model|cut:' '|lower|add:'-detail' %}"> ADD {{ model|upper }}
            <img src="{% static 'admin/img/tooltag-add.svg' %}" alt="">
        </a>
    </div>

    <div class="list table-responsive">
        <table class="table table-striped table-hover" id="list-data">
            <thead class="thead-light" >
                {% for key in keys %}
                    <th class="thead-tracker">
                        {{ key|upper }}
                    </th>
                {% endfor %}
            </thead>

            <tbody>
                {% for obj in queryset %}
                    <tr>
                        {% for k, v in obj.items %}
                            {% if k == link %}
                                <td> <a href="{% url namespace|add:':'|add:model|cut:' '|lower|add:'-detail' pk=obj.id %}"> {{ v }} </a> </td>
                            {% elif k in keys %}
                                <td> {{ v }} </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock right_pane %}