tracker/accounts/urls.py
from django.urls import path
from accounts.views import SignUpView, UpdateProfileView, ResetPasswordView, LoginView, LogoutView, TeamView, UserView

app_name = 'accounts'

urlpatterns = [
        path('login/', LoginView.as_view(), name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('signup/', SignUpView.as_view(), name='signup'),
        path('update_profile/', UpdateProfileView.as_view(), name='update_profile'),
        path('reset_password/', ResetPasswordView.as_view(), name='reset_password'),
        path('profile/', ResetPasswordView.as_view(), name='profile'),
        path('update_password/', ResetPasswordView.as_view(), name='update_password'),
        
        path('users/', UserView.as_view(), name='user-list'),
        path('user/add/', UserView.as_view(), {"action":"add"}, name='user-detail'),
        path('user/<int:pk>/change/', UserView.as_view(), {"action":"change"}, name='user-detail'),
        path('user/<int:pk>/delete/', UserView.as_view(), {"action":"delete"}, name='user-delete'),

        path('teams/', TeamView.as_view(), name='team-list'),
        path('team/add/', TeamView.as_view(), {"action": "add"}, name='team-detail'),
        path('team/<int:pk>/change/', TeamView.as_view(), {"action": "change"}, name='team-detail'),
        path('team/<int:pk>/delete/', TeamView.as_view(), {"action": "delete"}, name='team-delete'),
]

tracker/home/urls.py
from django.urls import include, path

from home.views import HomeView, AboutView, AdminView

app_name = 'home'

urlpatterns = [
    path('admin/', AdminView.as_view(), name='admin'),
    path('about/', AboutView.as_view(), name='about'),
    path('', HomeView.as_view(), name='home')
]

tracker/projects/urls.py
from django.urls import include, path

from projects.views import ProjectView, RolesView, PermissionsView

app_name = 'projects'

urlpatterns = [
    path('', ProjectView.as_view(), name='project-list'),
    path('add/', ProjectView.as_view(), {"action":"add"}, name='project-detail'),
    path('<int:pk>/change/', ProjectView.as_view(), {"action":"change"}, name='project-detail'),
    path('<int:pk>/delete/', ProjectView.as_view(), {"action":"delete"}, name='project-delete'),

    path('roles', RolesView.as_view(), name='roles-list'),
    path('roles/add/', RolesView.as_view(), {"action":"add"}, name='roles-detail'),
    path('roles/<int:pk>/change/', RolesView.as_view(), {"action":"change"}, name='roles-detail'),
    path('roles/<int:pk>/delete/', RolesView.as_view(), {"action":"delete"}, name='roles-delete'),

    path('permissions', PermissionsView.as_view(), name='permissions-list'),
    path('permissions/add/', PermissionsView.as_view(), {"action":"add"}, name='permissions-detail'),
    path('permissions/<int:pk>/change/', PermissionsView.as_view(), {"action":"change"}, name='permissions-detail'),
    path('permissions/<int:pk>/delete/', PermissionsView.as_view(), {"action":"delete"}, name='permissions-delete'),
]

tracker/tasks/urls.py
from django.urls import include, path

from tasks.views import TaskTypeView, TaskView

app_name = 'tasks'

urlpatterns = [
    path('create/', TaskView.as_view(), {"action": "create" }, name='create'),
    path('search/', TaskView.as_view(), {"action": "search" }, name='search'),
    path('browse/<task_key>/', TaskView.as_view(), {"action":"browse"}, name='browse'),
    path('browse/<task_key>/edit/', TaskView.as_view(), {"action":"edit"}, name='edit'),
]

tracker/tracker/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/projects/', include('projects.urls', namespace='projects')),
    path('admin/workflow/', include('workflows.urls', namespace='workflows')),
    path('admin/tasks/', include('tasks.admin.urls', namespace='admin_tasks')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('', include('home.urls', namespace='home')),
    path('djadmin/', admin.site.urls),
]

tracker/workflows/urls.py
from django.urls import include, path

from workflows.views import WorkflowView, WorkflowStatesView, WorkflowTransitionsView

app_name = 'workflows'

urlpatterns = [
    path('', WorkflowView.as_view(), name='workflow-list'),
    path('add/', WorkflowView.as_view(), {"action":"add"}, name='workflow-detail'),
    path('<int:pk>/change/', WorkflowView.as_view(), {"action":"change"}, name='workflow-detail'),
    path('<int:pk>/delete/', WorkflowView.as_view(), {"action":"delete"}, name='workflow-delete'),

    path('states/', WorkflowStatesView.as_view(), name='workflowstates-list'),
    path('states/add/', WorkflowStatesView.as_view(), {"action":"add"}, name='workflowstates-detail'),
    path('states/<int:pk>/change/', WorkflowStatesView.as_view(), {"action":"change"}, name='workflowstates-detail'),
    path('states/<int:pk>/delete/', WorkflowStatesView.as_view(), {"action":"delete"}, name='workflowstates-delete'),

    path('transitions/', WorkflowTransitionsView.as_view(), name='workflowtransitions-list'),
    path('transitions/add/', WorkflowTransitionsView.as_view(), {"action":"add"}, name='workflowtransitions-detail'),
    path('transitions/<int:pk>/change/', WorkflowTransitionsView.as_view(), {"action":"change"}, name='workflowtransitions-detail'),
    path('transitions/<int:pk>/delete/', WorkflowTransitionsView.as_view(), {"action":"delete"}, name='workflowtransitions-delete'),    
]

tracker/home/models.py
from django.db import models

# Create your models here.

tracker/home/views.py
import logging

from django.shortcuts import render
from django.views.generic import TemplateView, View
from tasks.models import Task
from projects.models import Project
from tasks.models import Filters
from accounts.models import User

logger = logging.getLogger(__name__)


# Create your views here.
class HomeView(View):
    template_name = "home.html"
    login_template_name = "dashboard.html"
    fields = ['id', 'name']
    task_fields = ['key', 'tasktype__name', 'summary', 'priority', 'state']
    task_ui_fields = ['key', 'type', 'summary', 'priority', 'state']

    def _get_all_projects(self):
        return list(Project.objects.filter(status=True).values(*self.fields))

    def _get_user_filters(self, user):
        return list(Filters.objects.filter(created_by=user, status=True).values(*self.fields))

    def _get_system_filters(self, username):
        try:
            user = User.objects.get(username=username)
            return list(Filters.objects.filter(created_by=user, status=True).values(*self.fields))
        except Exception as e:
            logger.exception(e)
            user = None
            return []

    def _get_user_assigned_tasks(self, user):
        queryset = Task.objects.filter(assignee=user).values(*self.task_fields)
        return queryset

    def _get_user_reported_tasks(self, user):
        queryset = Task.objects.filter(created_by=user).values(*self.task_fields)
        return queryset

    def get(self, request):
        context={}
        if request.user.is_authenticated:
            username = request.user.username
            projects = self._get_all_projects()
            system_filters = self._get_system_filters(username="admin")
            user_filters = self._get_user_filters(request.user)
            request.session[username] = {
                "projects" : projects,
                "filters": system_filters + user_filters,
            }
            context["assigned_filters"] = self._get_user_assigned_tasks(request.user)
            context["reported_filters"] = self._get_user_reported_tasks(request.user)
            context["task_fields"] = self.task_ui_fields

            # Fetch all filters created by user and system and add in session.
            template = self.login_template_name
        else:
            try:
                error = request.session.pop("login_error")
            except KeyError:
                error = None
            if error:
                context["error"] = error
            template = self.template_name
        return render(request, template, context)

class AboutView(TemplateView):
    template_name = "about.html"

class AdminView(TemplateView):
    template_name = "admin.html"

tracker/home/templates/about.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
  welcome {{user}}
{% endblock content %}

tracker/home/templates/admin.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- Adding Left Pane -->
    <nav class="col-sm-2 bg-light sidebar ">
    {% block left_pane %}
      <ul class="nav flex-column">
        <li class="nav-item left-pane-headings">
          <a href="{% url 'projects:project-list' %}"> 
            <h5 class="text-muted"> Administration </h5> 
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'accounts:user-list' %}"> Users </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'accounts:team-list' %}"> Teams </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'projects:project-list' %}"> Projects </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin_tasks:tasktype-list' %}"> Tasks Type </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'projects:permissions-list' %}"> Permissions </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'projects:roles-list' %}"> Roles </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'workflows:workflow-list' %}"> Workflows </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'workflows:workflowstates-list' %}"> Workflows States </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'workflows:workflowtransitions-list' %}"> Workflows Transitions </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin_tasks:filters-list' %}"> Filters </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'admin_tasks:taskdependency-list' %}"> TaskDependency </a>
        </li>
      </ul>
    {% endblock left_pane %}
    </nav>

    <!-- Adding Right Pane -->
    <main role="main" class="col-sm-9">
      {% block right_pane %}
      {% endblock %}
    </main>
  </div>
</div>
{% endblock content %}

tracker/home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {{ page_title | default:"Tracker" }}
        {% endblock title %}
    </title>

    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}

    {% block js %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
    {% block header %}
        <p>
            PlaceHolder for Headers, Replace it with actual Content..!!
        </p>
    {% endblock %}

    {% block body %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block lazyjs %}
    {% endblock %}
</body>
</html>

tracker/home/templates/dashboard.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}
{% load extras %}


{% block title %} Home {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card home-card">
                    <div class="card-header">
                        <h5 class="card-tracker"> Introduction </h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Welcome to Tracker Pvt. Ltd. </h5>
                        <p class="card-text"> Not sure where to start? Check out the Tracker Guide ---->
                        <a href="#" class="btn btn-link">Here </a>  </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card home-card">
                    <div class="card-header">
                        <h5 class="card-tracker"> Assigned To Me </h5>
                    </div>
                    <div class="card-body">
                        <table class="table table-sm table-striped table-hover" id="list-data">
                            <thead class="thead-dark">
                                {% for key in task_fields %} <th class="thead-tracker"> {{ key|upper }} </th> {% endfor %}
                            </thead>
                            <tbody>
                                {% for obj in assigned_filters %}
                                    <tr>
                                        {% for k, v in obj.items %}
                                            {% if k == "key" %}
                                                <td class="home-card-td"> <a href="{% url 'tasks:browse' task_key=v %}"> {{ v }} </a> </td>
                                            {% else %}
                                                <td class="home-card-td"> {{ v }} </td>
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card home-card">
            <div class="card-header">
                <h5 class="card-tracker"> Reported By Me </h5>
            </div>
            <div class="card-body">
                <div class="list table-responsive">
                    <table class="table table-sm table-striped table-hover" id="list-data">
                        <thead>
                            {% for key in task_fields %} <th id="tracker-head" class="thead-tracker"> {{ key|upper }} </th> {% endfor %}
                        </thead>
                        <tbody>
                            {% for obj in reported_filters %}
                                <tr>
                                    {% for k, v in obj.items %}
                                        {% if k == "key" %}
                                            <td class="home-card-td"> <a href="{% url 'tasks:browse' task_key=v %}"> {{ v }} </a> </td>
                                        {% else %}
                                            <td class="home-card-td"> {{ v }} </td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

tracker/home/templates/headers.html
{% extends 'base.html' %}

{% block header %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'home:home' %}">@ProjectManagement</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Issues</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
{% endblock %}

tracker/home/templates/home.html
<!-- templates/home.html-->
{% extends 'headers.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block customjs %}
  <script type="text/javascript">
    $(function(){
    $('#loginModal').modal({
      show: true,
      focus: true
    });
    $('#loginModal').on('hide.bs.modal', function(e){
        $('#login_error').val("");
    });
    });
  </script>
{% endblock %}

{% block content %}
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <form action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
        <div class="modal-body">
        <div class="error">
          <p id="login_error"> {{ error }}</p>
        </div>
          <div class="login">
            <div class="form-group row">
              <label for="id_username" class="col-sm-3 col-form-label">Username: </label>
              <input type="text" class="form-control col-sm-8" name="username" id="id_username" maxlength="50" autofocus required>
            </div>
            <div class="form-group row">
                <label for="id_password" class="col-sm-3 col-form-label">Password: </label>
                <input type="password" name="password" id="id_password" class="form-control col-sm-8">
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Login</button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="media top-image">
    <img src="{% static 'images/people.png' %}" class="mr-3" alt="" sizes="" srcset="">
    <div class="media-body" style="margin-left: 20px;">
      <h1 class="mt-6" style="margin-top:25px;"> Less Chaos </h1>
      <h1 class="mt-6" style="margin-left:100px;"> More Outcomes </h1>
      <h3 class="mt-2"> Project Management helps teams manage </h3>
      <ul>
        <li> Software Releases </li>
        <li> Marketing Goals </li>
        <li> Timely Deliveries </li>
        <li> Tasks Management </li>
        <li> Nice Reporting </li>
      </ul>
    </div>
  </div>

  <div class="middle">
    <h2 class="text"> Designed with thoughtful approach for more productivity. </h2>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0">Unlimited Projects, Tasks & Users</h5>
        <p>Bring all the projects & teams together on an all in one collaborative work management software.</p>
      </div>
    </div>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0"> Simplified Project Management </h5>
        <p> Add value to your business with successful project delivery. Build realistic project plans and monitor execution seamlessly. </p>
      </div>
    </div>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0">Improve Project Delivery</h5>
        <p>Accelerate project delivery with real time collaboration among the team to ensure projects are delivered on time & with in budget while maintaining optimum quality.</p>
      </div>
    </div>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0"> Robust Resource and Task Planning. </h5>
        <p>Roles and availability based task planning for optimum resource utilization. Manage holidays and leaves in real time to prevent delays.</p>
      </div>
    </div>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0"> Subtasks Creation </h5>
        <p> Breakdown & organize your project tasks for added clarity and managing task wise dependencies effectively.</p>
      </div>
    </div>
    <div class="media middle-text">
      <img class="mr-3" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0"> Workflow Management </h5>
        <p> Give your projects a logical and unique workflow for meaningful execution.</p>
      </div>
    </div>
  </div>

  <div class="media centre-image">
    <img src="{% static 'images/ideas.png' %}" class="mr-3" alt="" sizes="" srcset="">
  </div>

  <div class="card-deck bottom">
      <div class="card border-0 card-center">
        <img class="card-image-top card-image-width" src="{% static 'images/powerfull.png' %}" alt="Generic placeholder image">
        <div class="card-body">
          <h5 class="card-title">Powerfull</h5>
          <p class="card-text">Customize everything easily.You are in full control</p>
        </div>
      </div>
      <div class="card border-0 card-center">
          <img class="card-image-top card-image-width" src="{% static 'images/simple.png' %}" alt="Generic placeholder image">
          <div class="card-body">
            <h5 class="card-title">Simple & Intuitive</h5>
            <p class="card-text">Figuring out the tool is ridiculously easy.</p>
          </div>
      </div>
      <div class="card border-0 card-center">
          <img class="card-image-top card-image-width" src="{% static 'images/designed.png' %}" alt="Generic placeholder image">
          <div class="card-body">
            <h5 class="card-title">Highly Designed</h5>
            <p class="card-text">Simple & Gorgeous! Beautiful to look at all day long</p>
          </div>
      </div>
      <div class="card border-0 card-center">
          <img class="card-image-top card-image-width" src="{% static 'images/customizable.png' %}" alt="Generic placeholder image">
          <div class="card-body">
            <h5 class="card-title">customizable</h5>
            <p class="card-text">Give each project its own personality </p>
          </div>
      </div>
  </div>
</div>
{% endblock %}